# Generated by Django 5.0.7 on 2024-08-14 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название Поста')),
                ('image', models.ImageField(null=True, upload_to='static/imgblog', verbose_name='Картинка')),
                ('desc', models.TextField(verbose_name='Содержимое поста')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
