# Generated by Django 5.0.7 on 2024-08-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_image_comment_on_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_on_post',
            name='title',
        ),
    ]
