# Generated by Django 5.0.7 on 2024-08-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_on_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/blogapp/blogimg', verbose_name='Картинка'),
        ),
    ]
