# Generated by Django 5.1 on 2024-08-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_image_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOnBlogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='like')),
                ('likeid', models.IntegerField(null=True, verbose_name='откуда лайкнули')),
                ('rev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost', verbose_name='Блог который лайкнули')),
                ('uslike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тот кто лайкнул отзыв')),
            ],
        ),
    ]
