# Generated by Django 5.1 on 2024-08-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likeonblogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeonblogpost',
            old_name='rev',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='likeonblogpost',
            old_name='uslike',
            new_name='userlike',
        ),
    ]
