# Generated by Django 5.1 on 2024-08-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_rev_likeonblogpost_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeonblogpost',
            name='likeid',
        ),
    ]
