# Generated by Django 5.1 on 2024-08-19 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_likeonblogpost_likeid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='like')),
                ('Comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment_on_post', verbose_name='Блог который лайкнули')),
                ('userlike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тот кто лайкнул отзыв')),
            ],
        ),
    ]
