# Generated by Django 5.1 on 2024-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userbet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='iconuser',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/profile/profileimg', verbose_name='Иконка профиля'),
        ),
    ]
