# Generated by Django 5.1 on 2024-08-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_userbet_iconuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbet',
            old_name='user',
            new_name='User',
        ),
    ]
