# Generated by Django 5.1 on 2024-08-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_userbet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyoncomm',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userbet'),
        ),
    ]
